initial_pose:
  position:
    x: -1.883
    y: -0.010
    z: 0.0
  yaw: -1.50   # Radiant

rooms:

  office_101:
    name: "Büro 101"
    waypoints:

      - position:
          x: 6.5
          y: 3.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Vor Büroeingang"

      - position:
          x: 10.0
          y: 4.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Büro Endposition"

  office_102:
    name: "Büro 102"
    waypoints:

      - position:
          x: -2.5
          y: 2.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Vor Bürotür"

      - position:
          x: -6.0
          y: -5.6
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Büro Endposition"

  office_103:
    name: "Büro oben Mitte"
    waypoints:

      - position:
          x: -12.5
          y: 2.5
          z: 0.0
        yaw: 0.8
        check_pedestrian: true
        description: "Vor Bürotür"

      - position:
          x: -15.0
          y: 6.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Büro Endposition"

  office_104:
    name: "Büro 104 Ecke links"
    waypoints:

      - position:
          x: -23.5
          y: 2.5
          z: 0.0
        yaw: 0.8
        check_pedestrian: true
        description: "Vor Bürotür"

      - position:
          x: -25.0
          y: 6.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Büro Endposition"

  lab_203:
    name: "Labor links"
    waypoints:


      - position:
          x: -9.0
          y: 3.0
          z: 0.0
        yaw: 0.7
        check_pedestrian: true
        description: "Im Flur"
    
      - position:
          x: -23.5
          y: 2.5
          z: 0.0
        yaw: 0.8
        check_pedestrian: true
        description: "Vor der Tür zum Labor"

      - position:
          x: -26.0
          y: -2.5
          z: 0.0
        yaw: 0.0
        check_pedestrian: true
        description: "Im Labor"

     

  lab_204:
    name: "Labor unten Mitte"
    waypoints:

      - position:
          x: -2.4
          y: -2.2
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "An der Tür zum Labor"

      - position:
          x: -7
          y: -4.5
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Labor Endposition"

  lab_205:
    name: "Labor unten Rechts"
    waypoints:

      - position:
          x:  5.0
          y: -2.8
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "An der Tuer zum Flur"

      - position:
          x: 15.0
          y: -2.8
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "An der Tuer zum Labor"

      - position:
          x: 19.0
          y: -4.0
          z: 0.0
        yaw: 3.14
        check_pedestrian: true
        description: "Labor Endposition"


  entrance:
    name: "Haupteingang"
    waypoints:

      - position:
          x: 0.0
          y: 0.0
          z: 0.0
        yaw: 0.0
        check_pedestrian: false
        description: "Eingangsbereich"